=== south-lacrosse/xml-data/clubs.dtd
<?xml version='1.0' encoding="UTF-8"?>

<!ENTITY quot    "&#34;"> <!--  quotation mark, U+0022 ISOnum -->
<!ENTITY amp     "&#38;#38;"> <!--  ampersand, U+0026 ISOnum -->
<!ENTITY lt      "&#38;#60;"> <!--  less-than sign, U+003C ISOnum -->
<!ENTITY gt      "&#62;"> <!--  greater-than sign, U+003E ISOnum -->
<!ENTITY apos	 "&#39;"> <!--  apostrophe = APL quote, U+0027 ISOnum -->

<!ENTITY nbsp   "&#160;"> <!-- no-break space = non-breaking space,
                                  U+00A0 ISOnum -->
<!ENTITY pound  "&#163;"> <!-- pound sign, U+00A3 ISOnum -->
<!ENTITY copy   "&#169;"> <!-- copyright sign, U+00A9 ISOnum -->

<!ENTITY laquo  "&#171;"> <!-- left-pointing double angle quotation mark
                                  = left pointing guillemet, U+00AB ISOnum -->
<!ENTITY raquo  "&#187;"> <!-- right-pointing double angle quotation mark
                                  = right pointing guillemet, U+00BB ISOnum -->
<!ENTITY frac14 "&#188;"> <!-- vulgar fraction one quarter
                                  = fraction one quarter, U+00BC ISOnum -->
<!ENTITY frac12 "&#189;"> <!-- vulgar fraction one half
                                  = fraction one half, U+00BD ISOnum -->
<!ENTITY frac34 "&#190;"> <!-- vulgar fraction three quarters
                                  = fraction three quarters, U+00BE ISOnum -->
<!ENTITY frac13 "&#x2153;">                                  
<!ENTITY ndash  "&#8211;"> <!-- en dash, U+2013 ISOpub -->
<!ENTITY mdash  "&#8212;"> <!-- em dash, U+2014 ISOpub -->
<!ENTITY lsquo  "&#8216;"> <!-- left single quotation mark,
                                    U+2018 ISOnum -->
<!ENTITY rsquo  "&#8217;"> <!-- right single quotation mark,
                                    U+2019 ISOnum -->
<!ENTITY ldquo  "&#8220;"> <!-- left double quotation mark,
                                    U+201C ISOnum -->
<!ENTITY rdquo  "&#8221;"> <!-- right double quotation mark,
                                    U+201D ISOnum -->                                  

<!-- club information -->

<!ENTITY % inline "a | b | br | email | img">
<!ENTITY % Inline "(#PCDATA | %inline; )*">
<!ENTITY % Flow "( #PCDATA | %inline; | p)*">

<!ELEMENT clubs ( club+ ) >

<!ELEMENT club ( name, description?, website?, twitter?, ground*, colours?, ( contact | section)* ) >
<!ATTLIST club
	id ID #REQUIRED 
	founded NMTOKEN #IMPLIED 
	modified NMTOKEN #REQUIRED
	path NMTOKEN #IMPLIED
>

<!ELEMENT name ( #PCDATA ) >
<!ATTLIST name
	long CDATA #IMPLIED
	short CDATA #IMPLIED
	small CDATA #IMPLIED
	minimal CDATA #IMPLIED
>
<!ELEMENT description %Flow; >
<!ELEMENT website ( #PCDATA ) >
<!ELEMENT twitter ( #PCDATA ) >

<!ELEMENT ground ( name?, address, tel?, pitch?, note?, directions? ) >
<!ATTLIST ground 
	lat NMTOKEN #REQUIRED
	long NMTOKEN #REQUIRED
>

<!ELEMENT address ( street*, locality?, region?, postcode?) >
<!ELEMENT street ( #PCDATA ) >
<!ELEMENT locality ( #PCDATA ) >
<!ELEMENT region ( #PCDATA ) >
<!ELEMENT postcode ( #PCDATA ) >

<!ELEMENT pitch %Flow; >
<!ATTLIST pitch	type ( 3G | Sand-Astro | Astro ) #REQUIRED>

<!ELEMENT note %Flow; >

<!ELEMENT directions %Flow; >

<!ELEMENT a ( #PCDATA ) >
<!ATTLIST a href CDATA #IMPLIED >
<!ATTLIST a rel CDATA #IMPLIED >
<!ELEMENT br EMPTY >
<!ELEMENT b ( #PCDATA ) >
<!ELEMENT img EMPTY>
<!ATTLIST img
	alt CDATA #IMPLIED
	title CDATA #IMPLIED
	src CDATA #REQUIRED
	class CDATA #IMPLIED
	usemap CDATA #IMPLIED
	width CDATA #IMPLIED
	height CDATA #IMPLIED
>
<!ELEMENT p %Inline;>
<!ATTLIST p
	class CDATA #IMPLIED
>

<!ELEMENT section ( contact*, team* ) >
<!ATTLIST section type ( mens | juniors ) #REQUIRED >

<!ELEMENT team ( name, contact* ) >
<!ATTLIST team
	division CDATA #IMPLIED
	age ( U16 | U14 | U12 ) #IMPLIED
>

<!ELEMENT contact ( role, name?, email*, tel* ) >
<!ELEMENT role ( #PCDATA ) >
<!ELEMENT tel ( #PCDATA ) >
<!ATTLIST tel type ( home | work | messages ) #IMPLIED >
<!ELEMENT email ( #PCDATA ) >
<!ATTLIST email type ( alt | home | work ) #IMPLIED >

<!ELEMENT colours ( #PCDATA ) >

=== south-lacrosse/xml-data/clubs-edit.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE clubs PUBLIC "-//Southlacrosse//DTD Clubs 1.0//EN" "http://www.southlacrosse.org.uk/clubs.dtd">
<clubs>
 <club id="bath" modified="2020-09-25" founded="1983">
  <name>Bath</name>
  <website>http://bathlacrosse.com/wp/</website>
  <ground lat="51.361066" long="-2.377817">
   <address>
    <street>Odd Down Playing Fields</street>
    <street>Chelwood Drive</street>
    <street>Off Bloomfield Road</street>
    <locality>Bath</locality>
    <postcode>BA2 2PR</postcode>
   </address>
   <pitch type="3G"/>
   <note><p>Games are usually played on 3G, however some games are played on grass, and captains will notify visiting teams which pitch is being used.</p></note>
   <directions>
    <p><b>From M4 Jct 18</b> Follow signs to Bath, entering Bath on the A4. Turn left at the first main set
    of traffic lights into Cleveland Place/Bathwick Street. Turn right at the traffic lights at the end onto the
    A36. Follow this road until you get to the large Churchill Bridge roundabout, and turn left onto
    the A367 towards Radstock. After 0.7 miles use the right turn lane to turn right into Bloomfield Rd.
    After 1 mile turn left into Chelwood Drive, and the club is immediately on your left.</p>
	<p><b>By public transport</b> The ground is a 5-10 min bus ride away from Bath Spa Station. The number 4 bus stops at Noads Corner, which is just past the ground. From the station the bus stop is 150m left along Dorchester St. Also note you can pay using your contactless cards on First Bus.</p>
   </directions>
  </ground>
  <colours>Red with black trim</colours>
  <contact>
   <role>Secretary</role>
   <name>Gareth Davies</name>
   <email>secretary@bathlacrosse.com</email>
  </contact>
  <contact>
   <role>Match Secretary</role>
   <name>Nik Roberts</name>
   <email>nik.roberts@bathlacrosse.com</email>
   <tel>07734 725258</tel>
  </contact>
  <contact>
   <role>Club Captain</role>
    <name>Mark Lane</name>
    <email>captain@bathlacrosse.com</email>
    <tel>07547 768762</tel>
  </contact>
  <section type="mens">
   <team division="D2,L-Cot1">
    <name minimal="Bth">Bath</name>
    <contact>
      <role>Captain</role>
      <name>Luke Wilmot</name>
      <email>lukejwilmot@gmail.com</email>
      <tel>07933 187930</tel>
    </contact>
    <contact>
      <role>Vice Captain</role>
      <name>Alex George</name>
      <email>alexandergeorge500@gmail.com</email>
      <tel>07816 839794</tel>
    </contact>
   </team>
  </section>
 </club>
 <club id="bath-uni" modified="2020-09-25" founded="1995">
  <name long="University of Bath">Bath Uni</name>
  <website>https://www.thesubath.com/lacrosse/</website>
  <ground lat="51.380441" long="-2.330673">
   <address>
    <street>University of Bath</street>
    <street>Claverton Down</street>
    <locality>Bath</locality>
    <postcode>BA2 7AY</postcode>
   </address>
   <directions>
    <p>Games are played on the University Medical pitch. The easiest way to the pitch is through the main entrance on Claverton Down Road, turn left into South Car Park then walk to the pitch. Changing rooms are located in the centre of campus by the Founders Hall if required.</p>
    <p><img src="bath-uni.png" alt="Map of ground"/></p>
    <p>£2 parking for the day, there is free parking but it's a 5-10 minute walk away down Widcombe Hill.</p>
   </directions>
  </ground>
  <colours>Blue/yellow shirts, blue shorts</colours>
  <!-- 
  <contact>
   <role>Chair</role>
   <name>Josh Yeoman</name>
   <email>jay26@bath.ac.uk</email>
   <tel>07816 844173</tel>
  </contact>
  <contact>
   <role>Secretary</role>
   <name>Adnan Siddiquei</name>
   <email>as3547@bath.ac.uk</email>
   <tel>07535 500998</tel>
  </contact>
  -->
  <section type="mens">
   <team division="L-Cot2">
    <name minimal="BtUni">Bath Uni</name>
    <contact>
      <role>Captain</role>
      <name>Tom Stansfield</name>
      <email>ts2115@bath.ac.uk</email>
      <tel>07841 377388</tel>
    </contact>
    <contact>
      <role>Captain</role>
      <name>Billy Rawlins</name>
      <email>billyrawlins1414@gmail.com</email>
      <tel>07866 826813</tel>
    </contact>
   </team>
  </section>
 </club>
 <club id="birmingham-uni" modified="2019-12-31">
  <name long="University of Birmingham">Birmingham Uni</name>
  <ground lat="52.455371" long="-1.938024">
   <address>
    <street>Metchley Grass Pitches</street>
    <street>9 Pritchatts Road</street>
    <street>Pritchatts Park Village</street>
    <locality>Birmingham</locality>
    <postcode>B15 2QX</postcode>
   </address>
   <directions>
    <p>The pitches are behind number 9 Pritchatts Road, with the access road clearly signposted 'Pritchatts Park Village'. Head straight down to the bottom of the road and car park is on the left signposted 'Additional Parking'. Parking is free at weekends. Changing rooms are situated within the green portacabins, and the pitches are found after crossing a small bridge towards the tree line.</p>
   </directions>
  </ground>
  <colours>Red with gold trim</colours>
  <contact>
    <role>General Contact</role>
    <email>birminghamlacrosseuk@gmail.com</email>
  </contact>
  <contact>
    <role>Chair</role>
    <name>Lucy Pirkle</name>
    <email>lxp711@student.bham.ac.uk</email>
  </contact>
  <section type="mens">
   <team division="L-Mid">
    <name short="Birmingham" minimal="Bhm">Birmingham Uni</name>
    <contact>
      <role>Captain</role>
      <name>Oliver Bournes</name>
      <email>Oliverbournes@btinternet.com</email>
      <tel>07969 555726</tel>
    </contact>
   </team>
  </section>
 </club>
 <club id="bristol-city" modified="2020-10-08" founded="2007">
  <name>Bristol Bombers</name>
  <website>https://www.facebook.com/BristolBombersLacrosse/</website>
  <!-- 
  <website>https://www.bristolbombers.co.uk/</website>
   -->
  <ground lat="51.506646" long="-2.574400">
   <address>
    <street>Filton Sports &amp; Leisure Centre</street>
    <street>Elm Park</street>
    <locality>Filton</locality>
    <region>Bristol</region>
    <postcode>BS34 7PS</postcode>
   </address>
   <!--
   <directions>
    <p><b>By Public Transport</b> The nearest staion is <a rel="nofollow" href="https://www.nationalrail.co.uk/stations/FIT/details.html">Filton Abbey Wood</a>. From the station you can enter the ground at the <a rel="nofollow" href="https://www.google.com/maps/dir/Filton+Abbey+Wood,+Stoke+Gifford,+Bristol+BS34+7LJ/51.5067869,-2.5702618/@51.5059124,-2.5704881,16z/data=!4m9!4m8!1m5!1m1!1s0x487191c88fb332f7:0xc0ce3149aee89f36!2m2!1d-2.5638416!2d51.5033536!1m0!3e2">rear entrance in Shellard Road</a> which will save you &frac14; mile walk, and only takes 10 minutes.
    <br/>Filton Abbey Wood is 1 stop from <a rel="nofollow" href="https://www.nationalrail.co.uk/stations/FIT/details.html">Bristol Parkway</a> (which is also only a 5 minute taxi ride from the ground) but trains are infrequent, and 10 minutes from <a rel="nofollow" href="https://www.nationalrail.co.uk/stations/BPW/details.html">Bristol Temple Meads</a> (every 20 mins).</p>
  </directions>
  -->
   </ground>
  <colours>Black</colours>
  <contact>
   <role>General Contact</role>
   <email>bristolbombers@hotmail.co.uk</email>
  </contact>

  <contact>
   <role>Chair</role>
      <name>Lenni Hoffman</name>
      <email>lennart.e.hoffman@gmail.com</email>
  </contact>
  <contact>
   <role>Vice Chair</role>
      <name>Owen Edwards</name>
      <email>owene94@gmail.com</email>
      <tel>07882 204315</tel>
  </contact>
  <section type="mens">
   <team division="D2,L-Cot1">
    <name small="Bristol" minimal="Bri">Bristol Bombers</name>
    <contact>
      <role>1st Team Captain</role>
      <name>Tom Pratt</name>
      <email>tom.pratt985@gmail.com</email>
    </contact>
   </team>
   <team division="L-Cot2">
    <name small="Bristol 2" minimal="Bri 2">Bristol Bombers 2</name>
     <contact>
      <role>2nd Team Captain</role>
      <name>Sean Alexander</name>
      <email>sean.daniel.alexander@gmail.com</email>
     </contact>
   </team>
  </section>
 </club>
 <club id="army" modified="2020-09-23">
  <name>British Army</name>
  <website>https://www.facebook.com/groups/39102440479/</website>
  <ground lat="51.265846" long="-0.749592">
    <address>
     <street>Aldershot Garrison Sports Centre</street>
     <street>Rawlinson Rd</street>
     <region>Aldershot</region>
     <postcode>GU11 2LQ</postcode>
    </address>
    <note>
    <p>Games are usually played on the Queens Avenue Sports Pitches, but contact Sgt Donaldson or Lt Barrigan by emails listed for detailed directions as pitch location can be changed, but will always be in the Aldershot Garrison area.</p>
    </note>
  </ground>
  <colours>Red</colours>
  <contact>
   <role>Chair</role>
   <name>Maj Brett Bader</name>
   <email>brettbader@aol.com</email>
   <tel>07810 503533</tel>
  </contact>
  <contact>
   <role>Secretary</role>
   <name>Lt Chad Barrigan</name>
   <email>Charles.Barrigan824@mod.gov.uk</email>
  </contact>
  <contact>
   <role>Game Contact</role>
   <name>Sgt Gavin Donaldson</name>
   <email>up834305@myport.ac.uk</email>
   <tel>07547 819023</tel>
  </contact>
  <section type="mens">
   <team>
    <name short="Army">British Army</name>
    <contact>
     <role>Captain</role>
     <name>Maj Dan Murphy</name>
    </contact>
   </team>
  </section>
 </club>
 <club id="bucks" modified="2019-09-23" founded="1912">
  <name>Buckhurst Hill</name>
  <website>https://www.buckslacrosse.co.uk/</website>
  <twitter>@BuckhurstHillLC</twitter>
  <ground lat="51.627582" long="0.057088">
   <address>
    <street>Buckhurst Hill Cricket &amp; Lacrosse Club</street>
    <street>Roding Lane</street>
    <locality>Buckhurst Hill</locality>
    <region>Essex</region>
    <postcode>IG9 6BJ</postcode>
   </address>
   <directions>
    <p><b>From M25</b> At Jct 26 take the A121 South towards Loughton. After 5 miles turn left down Palmerston Road (B170)
